version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=monitoring
    volumes:
      - D:\Projects\step3\sql:/docker-entrypoint-initdb.d
    networks:
      - postgres-reporter
  hbase:
    image: dajobe/hbase
    container_name: hbase
    hostname: hbase
    networks:
      - hbase-tracker
      - hbase-reporter
  pixel-tracker:
    image: openjdk:8-jdk
    container_name: pixel-tracker
    hostname: tracker
    volumes:
      - D:\Projects\step3\tracking\target\tracking-0.0.1-SNAPSHOT.jar:/opt/tracker.jar
    command: java -jar -Dspring.profiles.active=docker /opt/tracker.jar
    ports:
      - "8081:8081"
    networks:
      - hbase-tracker
    depends_on:
      - hbase
    environment:
      - HBASE_QUORUM=hbase:2181
      - HBASE_ROOT_DIR=file:/data/hbase
      - HBASE_NODEPARENT=/hbase
  reporter:
    image: openjdk:11-jdk
    container_name: reporter
    networks:
      - hbase-reporter
      - postgres-reporter
    volumes:
      - D:\Projects\step3\reporter\target\reporter-0.0.1-SNAPSHOT.jar:/opt/reporter.jar
    command: java -jar -Dspring.profiles.active=docker /opt/reporter.jar
    depends_on:
      - hbase
networks:
  hbase-tracker:
    driver: bridge
  postgres-reporter:
    driver: bridge
  hbase-reporter:
    driver: bridge
