version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=monitoring
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
      - ../tracking/target/tracking-0.0.1-SNAPSHOT.jar:/lib/tracking-0.0.1-SNAPSHOT.jar
    ports:
      - "5432:5432"
  hbase:
    image: dajobe/hbase
    container_name: hbase
    hostname: hbase
    environment:
    - HBASE_DOCKER_HOSTNAME=hbase
  pixel-tracker:
    image: openjdk:11-jdk
    container_name: pixel-tracker
    hostname: tracker
    volumes:
      - ./tracking/target/tracking-0.0.1-SNAPSHOT.jar:/opt/tracker.jar
    command: java -jar -Dspring.profiles.active=docker /opt/tracker.jar
    ports:
      - "8081:8081"
    depends_on:
      - hbase
    environment:
      - HBASE_QUORUM=hbase:2181
      - HBASE_ROOT_DIR=file:////data/hbase
      - HBASE_NODEPARENT=/hbase
  reporter:
    image: openjdk:11-jdk
    container_name: reporter
    volumes:
      - ./reporter/target/reporter-0.0.1-SNAPSHOT.jar:/opt/reporter.jar
    command: java -Dspring.profiles.active=docker -cp "/opt/tracker.jar" -jar /opt/reporter.jar
    depends_on:
      - hbase
